services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URI: "https://api-chatapp.javaughnpryce.site"
    ports:
      - "9094:80"
    restart: unless-stopped

  backend:
    build:
      context: ./server
    ports:
      - "9093:5000"
    volumes:
      - server:/server/files
      - server:/server/logs
    env_file:
      - .env
    restart: unless-stopped

volumes:
  server:
